name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  set-up-environment:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g dotenv-cli
      - run: dotenv -e ${{ vars.PROPERTIES_FILE }} --debug
